### ISSUE TITLE
generator.py does not seem evaluate an event's status

### ISSUE THREAD

**Issue by Olf0** [derpeter/Conference-Mobile-Schedule#3]
Observed at the ["mobile" schedule of FrOSCon 2019](https://programm.froscon.de/mobil/): Events with the status "unconfirmed" are shown (while the ["desktop" schedule](https://programm.froscon.de/) does solely display events with the status "confirmed" or "scheduled", which is the expected behaviour).
Note that only these three stati were tested.

Looking at generator.py, it does not seem to evaluate an event's status at all.

Used back-end (for FrOSCon 2019): frab

**Comment by derpeter** [comment]
I'm not sure what you are refering to. The input data is the schedule.xml which only contains confirmed talks. The schedule.xml does not contain information on the states of acceptance see https://programm.froscon.de/2019/schedule.xml

**Comment by Olf0** [comment]
Well, I should have refrained more strongly from any technical interpretations after quickly glancing over the Python script.

I tested this (after the first observation) by toggling the status of two events from "confirmed" to "unconfirmed" and back a couple of times.
As the script does not access this data, I obviously ran into some caching / snapshot effects.
